version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-biblioteca
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: biblioteca
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
          test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-proot" ]
          timeout: 20s
          retries: 10
          interval: 5s

  app:
    build: .
    container_name: biblioteca-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/biblioteca_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
    ports:
      - "8081:8080"
    depends_on:
      mysql:
        condition: service_healthy
volumes:
  mysql_data:
